apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: alzheimer
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30420 # Access your Angular app on VM_IP:30420
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: alzheimer
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: nexus-creds
      containers:
      - name: frontend
        image: 192.168.80.128:30082/alzheimer-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
