apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: alzheimer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
      - name: ml-service
        image: 192.168.192.130:30083/alzheimer-ml-service:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "256m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: ml-service
  namespace: alzheimer
spec:
  selector:
    app: ml-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
